### ISSUE TITLE
Why word2vec is performed on train and test?

### ISSUE THREAD

**Issue by IbrahimSobh** [dandxy89/DeepLearning_MachineLearning#6]
Dear

I think the word2vec should be applied only on train data not the combined (train + test)  to simulate real life situations where test data is not available.

imdb_embedding_w2v.py
line 160: model.build_vocab(combined)

If so, how to initialize "embedding_weights"? what if the embedding_weights come from totally different text - different vocabulary - such as word2vec model by google or any other independent offline trained model?   

imdb_embedding_w2v.py
lione 195: weights=[embedding_weights]   

Regards

**Comment by dandxy89** [comment]
@IbrahimSobh 

The intention of the script was to provide an example for an issue on the Keras Issues log. Feel free to submit a pull request, I will happily update it. 

I think the primary reason I did so was due to the small data size.

Regarding your second question - there are examples on the Gensim website. See: [https://radimrehurek.com/gensim/models/word2vec.html](https://radimrehurek.com/gensim/models/word2vec.html)
